name = "undangan-krisnaindah"
compatibility_date = "2026-03-01"

[assets]
directory = "undangan"

[[d1_databases]]
binding = "DB"
database_name = "db-undangan"
database_id = "63ab1fbf-cfcd-4b4b-b139-b2edc6c73071"
